SET SERVEROUTPUT ON; 
SET SERVEROUTPUT OFF; 
BEGIN 
    DBMS_OUTPUT.PUT_LINE('HELLO WORLD');
    DBMS_OUTPUT.PUT_LINE('HELLO WORLD2');
    DBMS_OUTPUT.PUT('HELLO WORLD3');
    DBMS_OUTPUT.PUT('HELLO WORLD4');
    DBMS_OUTPUT.PUT_LINE();
END;
/
DECLARE
    EMP_ID NUMBER;
    EMP_NAME VARCHAR2(30);
BEGIN
    EMP_ID := 888;
    EMP_NAME :='배장남';
    DBMS_OUTPUT.PUT_LINE('EMP_ID :' || EMP_ID);
    DBMS_OUTPUT.PUT_LINE('EMP_NAME : '||EMP_NAME);
END;
/
DECLARE
    EMP_ID EMPLOYEE.EMP_ID%TYPE;
    EMP_NAME EMPLOYEE.EMP_NAME%TYPE;
BEGIN
    SELECT EMP_ID, EMP_NAME
    INTO EMP_ID, EMP_NAME
    FROM EMPLOYEE
    WHERE EMP_ID = '&EMP_ID';
    DBMS_OUTPUT.PUT_LINE('EMP_ID: ' || EMP_ID);
    DBMS_OUTPUT.PUT_LINE('EMP_NAME: '|| EMP_NAME);
END;
/
CREATE OR REPLACE PROCEDURE PRO_DEPT_INSERT
--DECLARE
IS
    MAXNDO DEPT.DEPTNO%TYPE;
    DNO DEPT.DEPTNO%TYPE;
BEGIN
SELECT MAX(DEPTNO) INTO MAXDNO FROM DEPT;
    insert  into DEPT (dname, DEPTNO, LOC) values ('EJ5', maxDNO+1, '서울');
    INSERT into DEPT (dname, DEPTNO, LOC) values ('EJ5', maxDNO+2, '서울');
    COMMIT;
END;
/


